### ISSUE TITLE
incorrect spacing in the end of the scrollable area

### ISSUE THREAD

**Issue by alvinchoi028** [Norserium/react-indiana-drag-scroll#48]
Hi, I am doing a Horizontal scroll, but the last item (the 30th) 's right red shadow cannot show on the screen

I tried to add padding/ margin/ border, still does not work.

sandbox: https://codesandbox.io/s/react-indiana-drag-scroll-default-forked-1xcxt

Also posted in
https://stackoverflow.com/questions/64661956/react-indiana-drag-scroll-the-shadow-of-the-last-item-not-shown

**Comment by Norserium** [comment]
Hello, @alvinchoi028! 

It's not the issue of react-indiana-drag-scroll. It's the peculiarity of browsers behavior [\[1\]](https://stackoverflow.com/questions/38993170/last-margin-padding-collapsing-in-flexbox-grid-layout),  [\[2\]](https://chenhuijing.com/blog/flexbox-and-padding/).

There are many different solutions to solve your exact problem.

Emulate margin by `:after` pseudo-element ([example](https://codesandbox.io/s/react-indiana-drag-scroll-emulate-margin-hwefp?file=/styles.css)):
```css
.container:after {
   content: "";
   flex: 0 0 10px;
}
.row:last-child {
   margin-right: 0;
}
```

Use `inline-block` ([example](https://codesandbox.io/s/react-indiana-drag-scroll-inline-block-0pner?file=/styles.css)):
```css
.container {
   display: block;
   white-space: nowrap;
}
.row {
   ...
   margin: 10px;
   display: inline-block;
}
```

Other solutions could be found in the question / article presented above.


_I've answered on your question on [stackoverflow.com](https://stackoverflow.com/a/64984389/12887853) also._
